module.exports = {
  emailConfig: {
    port: process.env.MAIL_PORT || 2525,
    host: process.env.MAIL_HOST || 'smtp.mailtrap.io',
    user: process.env.MAIL_USER || 'f2ef551b118f58',
    password: process.env.MAIL_PASS || 'bdb83c37ee7151',
    fromAddress: process.env.MAIL_FROM || 'e9cf477a87-4a141f@inbox.mailtrap.io',
    multiTemplate: true,
    multiLang: true,
    confirmTemplatePath: 'views/templates/confirmTemplate.html',
    multiLangConfirm: {
      ar: {
        subject: 'subject',
        body: {
          body: 'body',
          body1: 'body1',
          footer1: 'footer1',
          footer2: 'footer2',
          link: process.env.PUBLIC_URL || 'http://localhost:3000',
          achv_body: 'achv_body',
          achv_body0: 'achv_body0',
          achv_body1: 'achv_body1',
          achv_body2: 'achv_body2',
          achv_body3: 'achv_body3',
        },
        btn: {
          btn: 'btn',
          achv_btn: 'achv_btn',
          achv_btn1: 'achv_btn1',
        },
      },
    },
    confirmOptions: {
      subject: 'subject',
      body: {
        body: 'body',
        body1: 'body1',
        footer1: 'footer1',
        footer2: 'footer2',
        link: process.env.PUBLIC_URL || 'http://localhost:3000',
        achv_body: 'achv_body',
        achv_body0: 'achv_body0',
        achv_body1: 'achv_body1',
        achv_body2: 'achv_body2',
        achv_body3: 'achv_body3',
      },
      btn: {
        btn: 'btn',
        achv_btn: 'achv_btn',
        achv_btn1: 'achv_btn1',
      },
    },
    passwordOptions: {},
  },
};
